//
// Created by patatofour on 23/03/23.
//

#ifndef ARCADE_EVENTS_HPP
#define ARCADE_EVENTS_HPP
// --------------------------- Events related to the game ---------------------------//
#define QUIT           "QUIT"
#define CHANGE_GAME    "CHANGE_GAME"
#define CHANGE_GRAPHIC "CHANGE_GRAPH"
#define END_GAME       "GAME_END"
#define RESTART_GAME   "GAME_RESTART"

// --------------------------- Events related to keys ---------------------------//
#define MOUSE_CLICK_1         "MOUSE_KEY1_PRESSED"
#define MOUSE_CLICK_2         "MOUSE_KEY2_PRESSED"
#define MOUSE_CLICK_3         "MOUSE_KEY3_PRESSED"
#define MOUSE_CLICK_4         "MOUSE_KEY4_PRESSED"
#define MOUSE_CLICK_5         "MOUSE_KEY5_PRESSED"
#define KEY_A_PRESSED         "KEY_A_PRESSED"
#define KEY_B_PRESSED         "KEY_B_PRESSED"
#define KEY_C_PRESSED         "KEY_C_PRESSED"
#define KEY_D_PRESSED         "KEY_D_PRESSED"
#define KEY_E_PRESSED         "KEY_E_PRESSED"
#define KEY_F_PRESSED         "KEY_F_PRESSED"
#define KEY_G_PRESSED         "KEY_G_PRESSED"
#define KEY_H_PRESSED         "KEY_H_PRESSED"
#define KEY_I_PRESSED         "KEY_I_PRESSED"
#define KEY_J_PRESSED         "KEY_J_PRESSED"
#define KEY_K_PRESSED         "KEY_K_PRESSED"
#define KEY_L_PRESSED         "KEY_L_PRESSED"
#define KEY_M_PRESSED         "KEY_M_PRESSED"
#define KEY_N_PRESSED         "KEY_N_PRESSED"
#define KEY_O_PRESSED         "KEY_O_PRESSED"
#define KEY_P_PRESSED         "KEY_P_PRESSED"
#define KEY_Q_PRESSED         "KEY_Q_PRESSED"
#define KEY_R_PRESSED         "KEY_R_PRESSED"
#define KEY_S_PRESSED         "KEY_S_PRESSED"
#define KEY_T_PRESSED         "KEY_T_PRESSED"
#define KEY_U_PRESSED         "KEY_U_PRESSED"
#define KEY_V_PRESSED         "KEY_V_PRESSED"
#define KEY_W_PRESSED         "KEY_W_PRESSED"
#define KEY_X_PRESSED         "KEY_X_PRESSED"
#define KEY_Y_PRESSED         "KEY_Y_PRESSED"
#define KEY_Z_PRESSED         "KEY_Z_PRESSED"
#define KEY_0_PRESSED         "KEY_0_PRESSED"
#define KEY_1_PRESSED         "KEY_1_PRESSED"
#define KEY_2_PRESSED         "KEY_2_PRESSED"
#define KEY_3_PRESSED         "KEY_3_PRESSED"
#define KEY_4_PRESSED         "KEY_4_PRESSED"
#define KEY_5_PRESSED         "KEY_5_PRESSED"
#define KEY_6_PRESSED         "KEY_6_PRESSED"
#define KEY_7_PRESSED         "KEY_7_PRESSED"
#define KEY_8_PRESSED         "KEY_8_PRESSED"
#define KEY_9_PRESSED         "KEY_9_PRESSED"
#define KEY_UP_PRESSED        "KEY_UP_PRESSED"
#define KEY_DOWN_PRESSED      "KEY_DOWN_PRESSED"
#define KEY_LEFT_PRESSED      "KEY_LEFT_PRESSED"
#define KEY_RIGHT_PRESSED     "KEY_RIGHT_PRESSED"
#define KEY_SPACE_PRESSED     "KEY_SPACE_PRESSED"
#define KEY_ENTER_PRESSED     "KEY_ENTER_PRESSED"
#define KEY_ESC_PRESSED       "KEY_ESC_PRESSED"
#define KEY_TAB_PRESSED       "KEY_TAB_PRESSED"
#define KEY_BACKSPACE_PRESSED "KEY_BACKSPACE_PRESSED"
#define KEY_DELETE_PRESSED    "KEY_DELETE_PRESSED"
#define KEY_SHIFT_PRESSED     "KEY_SHIFT_PRESSED"
#define KEY_CTRL_PRESSED      "KEY_CTRL_PRESSED"
#define KEY_ALT_PRESSED       "KEY_ALT_PRESSED"
#define KEY_F1_PRESSED        "KEY_F1_PRESSED"
#define KEY_F2_PRESSED        "KEY_F2_PRESSED"
#define KEY_F3_PRESSED        "KEY_F3_PRESSED"
#define KEY_F4_PRESSED        "KEY_F4_PRESSED"
#define KEY_F5_PRESSED        "KEY_F5_PRESSED"
#define KEY_F6_PRESSED        "KEY_F6_PRESSED"
#define KEY_F7_PRESSED        "KEY_F7_PRESSED"
#define KEY_F8_PRESSED        "KEY_F8_PRESSED"
#define KEY_F9_PRESSED        "KEY_F9_PRESSED"
#define KEY_F10_PRESSED       "KEY_F10_PRESSED"
#define KEY_F11_PRESSED       "KEY_F11_PRESSED"
#define KEY_F12_PRESSED       "KEY_F12_PRESSED"

// --------------------------- Events related to the window ---------------------------//
#define WINDOW_CLOSE    "WINDOW_CLOSE"
#define WINDOW_RESIZE   "WINDOW_RESIZE"
#define WINDOW_MINIMIZE "WINDOW_MINIMIZE"
#define WINDOW_MAXIMIZE "WINDOW_MAXIMIZE"

#endif // ARCADE_EVENTS_HPP
